# Generated by Django 4.1.5 on 2023-01-25 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_purchaser_snack_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='snack',
            name='image_url',
            field=models.URLField(default='../static/src/blank_cereal_box.jpg'),
        ),
    ]
