# Generated by Django 4.1.5 on 2023-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_snack_rating_alter_snack_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='snack',
            name='image_url',
            field=models.URLField(blank=True, default='https://www.hitpromo.net/imageManager/show/ZBOX-MINCEREAL_blank2.jpg'),
        ),
    ]
